import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro', // This is the intro.md file
    {
      type: 'category',
      label: 'Frontend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend-api', // Matches the 'out' folder from your config
        },
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend-api', // Matches the 'out' folder from your config
        },
      ],
    },
  ],
};

export default sidebars;